### PR TITLE
Listen autoplay changes

### PR DESCRIPTION
**Pull request by wilav-dev**
Autoplay can be updated

### CODE REVIEW

**Comment by gusgard** [comment]
@wilav-dev what type of issue fixed this ?

**Comment by wilav-dev** [comment]
On blur, I want to stop autoPlay, but because it is not included in the useEffect, if i use autoPlay={isFocused}, it's not pausing.

**Comment by wilav-dev** [comment]
Could you publish changes to npm?

**Comment by gusgard** [comment]
@wilav-dev it was released in `3.0.17`

**Pull request merged**
